services:
    web-server:
        container_name: web-server
        image: nginx:1.27.5-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web_server/conf:/etc/nginx/conf.d
            - ./web_server/certs:/etc/nginx/certs
            - ./frontend:/usr/share/nginx/html
        networks:
            - reverse_proxy_network
        depends_on:
            - backend1
            - backend2
            - backend3
    backend1:
        container_name: test-api-1
        build: 
            context: ./backend
        ports:
            - "8001:8001"
        networks:
            - reverse_proxy_network
        entrypoint: [ "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8001" ]
    backend2:
        container_name: test-api-2
        build: 
            context: ./backend
        ports:
            - "8002:8002"
        networks:
            - reverse_proxy_network
        entrypoint: [ "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8002" ]
    backend3:
        container_name: test-api-3
        build: 
            context: ./backend
        ports:
            - "8003:8003"
        networks:
            - reverse_proxy_network
        entrypoint: [ "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "8003" ]
networks:
  reverse_proxy_network:
    name: reverse_proxy_network    
    driver: bridge
