services:
    web-server:
        container_name: web-server-container
        image: nginx:1.27.5-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./conf:/etc/nginx/conf.d
            - ./certs:/etc/nginx/certs
