services:
    web-server:
        container_name: web-server
        image: nginx:1.27.5-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./web_server/conf:/etc/nginx/conf.d
            - ./frontend:/usr/share/nginx/html
            - ./web_server/certs:/etc/nginx/certs
